# R for Travis CI: see documentation at https://docs.travis-ci.com/user/languages/r

branches:
  only:
  - main

language: r
r:
  - 4.1.2

warnings_are_errors: false

r_binary_packages:
- glmnet

bioc_packages:
- GENESIS

r_github_packages:
- xihaoli/STAAR
