// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Indiv_Score_Test_SMMAT_multi
List Indiv_Score_Test_SMMAT_multi(arma::sp_mat G, arma::mat P, arma::vec residuals, int n_pheno);
RcppExport SEXP _MultiSTAAR_Indiv_Score_Test_SMMAT_multi(SEXP GSEXP, SEXP PSEXP, SEXP residualsSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(Indiv_Score_Test_SMMAT_multi(G, P, residuals, n_pheno));
    return rcpp_result_gen;
END_RCPP
}
// Indiv_Score_Test_SMMAT_multi_sparse
List Indiv_Score_Test_SMMAT_multi_sparse(arma::sp_mat G, arma::sp_mat Sigma_i, arma::mat Sigma_iX, arma::mat cov, arma::vec residuals, int n_pheno);
RcppExport SEXP _MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse(SEXP GSEXP, SEXP Sigma_iSEXP, SEXP Sigma_iXSEXP, SEXP covSEXP, SEXP residualsSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_iX(Sigma_iXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(Indiv_Score_Test_SMMAT_multi_sparse(G, Sigma_i, Sigma_iX, cov, residuals, n_pheno));
    return rcpp_result_gen;
END_RCPP
}
// Indiv_Score_Test_SMMAT_multi_sparse_cond
List Indiv_Score_Test_SMMAT_multi_sparse_cond(arma::sp_mat G, arma::sp_mat Sigma_i, arma::mat Sigma_iX, arma::mat cov, arma::mat X_adj, arma::vec residuals, int n_pheno);
RcppExport SEXP _MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse_cond(SEXP GSEXP, SEXP Sigma_iSEXP, SEXP Sigma_iXSEXP, SEXP covSEXP, SEXP X_adjSEXP, SEXP residualsSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_iX(Sigma_iXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_adj(X_adjSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(Indiv_Score_Test_SMMAT_multi_sparse_cond(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, n_pheno));
    return rcpp_result_gen;
END_RCPP
}
// MultiSTAAR_O_SMMAT
arma::vec MultiSTAAR_O_SMMAT(arma::sp_mat G, arma::mat P, arma::vec residuals, arma::mat weights_B, arma::mat weights_S, arma::mat weights_A, arma::vec mac, int mac_thres, int n_pheno);
RcppExport SEXP _MultiSTAAR_MultiSTAAR_O_SMMAT(SEXP GSEXP, SEXP PSEXP, SEXP residualsSEXP, SEXP weights_BSEXP, SEXP weights_SSEXP, SEXP weights_ASEXP, SEXP macSEXP, SEXP mac_thresSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_B(weights_BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_S(weights_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_A(weights_ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mac(macSEXP);
    Rcpp::traits::input_parameter< int >::type mac_thres(mac_thresSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiSTAAR_O_SMMAT(G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno));
    return rcpp_result_gen;
END_RCPP
}
// MultiSTAAR_O_SMMAT_sparse
arma::vec MultiSTAAR_O_SMMAT_sparse(arma::sp_mat G, arma::sp_mat Sigma_i, arma::mat Sigma_iX, arma::mat cov, arma::vec residuals, arma::mat weights_B, arma::mat weights_S, arma::mat weights_A, arma::vec mac, int mac_thres, int n_pheno);
RcppExport SEXP _MultiSTAAR_MultiSTAAR_O_SMMAT_sparse(SEXP GSEXP, SEXP Sigma_iSEXP, SEXP Sigma_iXSEXP, SEXP covSEXP, SEXP residualsSEXP, SEXP weights_BSEXP, SEXP weights_SSEXP, SEXP weights_ASEXP, SEXP macSEXP, SEXP mac_thresSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_iX(Sigma_iXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_B(weights_BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_S(weights_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_A(weights_ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mac(macSEXP);
    Rcpp::traits::input_parameter< int >::type mac_thres(mac_thresSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiSTAAR_O_SMMAT_sparse(G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno));
    return rcpp_result_gen;
END_RCPP
}
// MultiSTAAR_O_SMMAT_sparse_cond
arma::vec MultiSTAAR_O_SMMAT_sparse_cond(arma::sp_mat G, arma::sp_mat Sigma_i, arma::mat Sigma_iX, arma::mat cov, arma::mat X_adj, arma::vec residuals, arma::mat weights_B, arma::mat weights_S, arma::mat weights_A, arma::vec mac, int mac_thres, int n_pheno);
RcppExport SEXP _MultiSTAAR_MultiSTAAR_O_SMMAT_sparse_cond(SEXP GSEXP, SEXP Sigma_iSEXP, SEXP Sigma_iXSEXP, SEXP covSEXP, SEXP X_adjSEXP, SEXP residualsSEXP, SEXP weights_BSEXP, SEXP weights_SSEXP, SEXP weights_ASEXP, SEXP macSEXP, SEXP mac_thresSEXP, SEXP n_phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Sigma_i(Sigma_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma_iX(Sigma_iXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_adj(X_adjSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_B(weights_BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_S(weights_SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weights_A(weights_ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mac(macSEXP);
    Rcpp::traits::input_parameter< int >::type mac_thres(mac_thresSEXP);
    Rcpp::traits::input_parameter< int >::type n_pheno(n_phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiSTAAR_O_SMMAT_sparse_cond(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiSTAAR_Indiv_Score_Test_SMMAT_multi", (DL_FUNC) &_MultiSTAAR_Indiv_Score_Test_SMMAT_multi, 4},
    {"_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse", (DL_FUNC) &_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse, 6},
    {"_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse_cond", (DL_FUNC) &_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse_cond, 7},
    {"_MultiSTAAR_MultiSTAAR_O_SMMAT", (DL_FUNC) &_MultiSTAAR_MultiSTAAR_O_SMMAT, 9},
    {"_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse", (DL_FUNC) &_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse, 11},
    {"_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse_cond", (DL_FUNC) &_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse_cond, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiSTAAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
