# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Indiv_Score_Test_SMMAT_multi <- function(G, P, residuals, n_pheno = 1L) {
    .Call(`_MultiSTAAR_Indiv_Score_Test_SMMAT_multi`, G, P, residuals, n_pheno)
}

Indiv_Score_Test_SMMAT_multi_sparse <- function(G, Sigma_i, Sigma_iX, cov, residuals, n_pheno = 1L) {
    .Call(`_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse`, G, Sigma_i, Sigma_iX, cov, residuals, n_pheno)
}

Indiv_Score_Test_SMMAT_multi_sparse_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, n_pheno = 1L) {
    .Call(`_MultiSTAAR_Indiv_Score_Test_SMMAT_multi_sparse_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals, n_pheno)
}

MultiSTAAR_O_SMMAT <- function(G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L, n_pheno = 1L) {
    .Call(`_MultiSTAAR_MultiSTAAR_O_SMMAT`, G, P, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno)
}

MultiSTAAR_O_SMMAT_sparse <- function(G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L, n_pheno = 1L) {
    .Call(`_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse`, G, Sigma_i, Sigma_iX, cov, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno)
}

MultiSTAAR_O_SMMAT_sparse_cond <- function(G, Sigma_i, Sigma_iX, cov, X_adj, residuals, weights_B, weights_S, weights_A, mac, mac_thres = 10L, n_pheno = 1L) {
    .Call(`_MultiSTAAR_MultiSTAAR_O_SMMAT_sparse_cond`, G, Sigma_i, Sigma_iX, cov, X_adj, residuals, weights_B, weights_S, weights_A, mac, mac_thres, n_pheno)
}

